<a href="https://colab.research.google.com/github/ichi-a00/google_colab/blob/main/%E6%95%99%E5%B8%AB%E3%81%AA%E3%81%97%E5%AD%A6%E7%BF%92_k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

k-means
クラスタリングの手法。データを複数のクラスタに分けて特徴を捉える。

１　人間がクラスタの数を決める
２ ランダムに割り当てて、重心に買い物をクラスタにする
3kuriaesu

In [3]:
df = pd.read_csv('convinience_store.csv')
df.head()

No  弁当・麺類    飲料  おにぎり・サンドイッチ  スイーツ  カップスープ    サラダ
0   1  25350  3650         8945     0    4867   8945
1   2  24500     0            0  1827       0      0
2   3  23050  5750        11570     0    7667  11570
3   4  22850  4100        10145     0    5467  10145
4   5  22500     0            0     0       0      0

In [4]:
x = df.drop('No', axis=1).values

In [6]:
x[:3]

array([[25350,  3650,  8945,     0,  4867,  8945],
       [24500,     0,     0,  1827,     0,     0],
       [23050,  5750, 11570,     0,  7667, 11570]])

In [7]:
from sklearn.cluster import KMeans

n_clusters クラスタ数

In [9]:
kmeans = KMeans(n_clusters=3, random_state=0)

In [10]:
kmeans.fit(x)

KMeans(n_clusters=3, random_state=0)

In [11]:
kmeans.cluster_centers_

array([[ 5043.5483871 ,  3486.41935484,  7017.74193548,  2206.        ,
         2512.90322581,  3509.12903226],
       [28681.25      ,  5637.66666667,  1298.75      ,  1271.        ,
         1770.875     ,   716.95833333],
       [17266.66666667,  2730.93333333, 10721.66666667,   590.86666667,
         3447.33333333,  9851.2       ]])

６次元に、３つのクラスタ

In [12]:
cluster = kmeans.predict(x)

In [13]:
cluster

array([2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 0,
       2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1], dtype=int32)

In [15]:
df_cluster = df.copy()
df_cluster['cluster'] = cluster

In [17]:
df_cluster

No  弁当・麺類     飲料  おにぎり・サンドイッチ  スイーツ  カップスープ    サラダ  cluster
0    1  25350   3650         8945     0    4867   8945        2
1    2  24500      0            0  1827       0      0        1
2    3  23050   5750        11570     0    7667  11570        2
3    4  22850   4100        10145     0    5467  10145        2
4    5  22500      0            0     0       0      0        1
..  ..    ...    ...          ...   ...     ...    ...      ...
65  66  25600   9725         2695   144    1621   1348        1
66  67  25400   5988            0   581     998      0        1
67  68  25100      0         3745  2911       0   1873        1
68  69  24700   8075            0  1451    1346      0        1
69  70  22700  11563         3270  1410    1927   1635        1

[70 rows x 8 columns]

クラスタに分けただけだとどう使うかわからん。
どのように活用するかは人間側が考慮する必要がある。

In [25]:
df_results = pd.DataFrame()

In [21]:
df_cluster[df_cluster['cluster']==0].mean().tolist()

[37.806451612903224,
 5043.548387096775,
 3486.4193548387098,
 7017.741935483871,
 2206.0,
 2512.9032258064517,
 3509.1290322580644,
 0.0]

In [26]:
df_results['c0'] = df_cluster[df_cluster['cluster']==0].mean().tolist()
df_results['c1'] = df_cluster[df_cluster['cluster']==1].mean().tolist()
df_results['c2'] = df_cluster[df_cluster['cluster']==2].mean().tolist()

In [27]:
df_results

c0            c1            c2
0    37.806452     46.250000     13.533333
1  5043.548387  28681.250000  17266.666667
2  3486.419355   5637.666667   2730.933333
3  7017.741935   1298.750000  10721.666667
4  2206.000000   1271.000000    590.866667
5  2512.903226   1770.875000   3447.333333
6  3509.129032    716.958333   9851.200000
7     0.000000      1.000000      2.000000

In [28]:
df_results = df_results.set_index(df_cluster.columns)

In [29]:
df_results

c0            c1            c2
No             37.806452     46.250000     13.533333
弁当・麺類        5043.548387  28681.250000  17266.666667
飲料           3486.419355   5637.666667   2730.933333
おにぎり・サンドイッチ  7017.741935   1298.750000  10721.666667
スイーツ         2206.000000   1271.000000    590.866667
カップスープ       2512.903226   1770.875000   3447.333333
サラダ          3509.129032    716.958333   9851.200000
cluster         0.000000      1.000000      2.000000

In [30]:
df_results = df_results.drop(['No', 'cluster']).T

In [31]:
df_results

弁当・麺類           飲料  ...       カップスープ          サラダ
c0   5043.548387  3486.419355  ...  2512.903226  3509.129032
c1  28681.250000  5637.666667  ...  1770.875000   716.958333
c2  17266.666667  2730.933333  ...  3447.333333  9851.200000

[3 rows x 6 columns]

目的を持ってクラスタリング後のデータを加工・分析をすることで、クラスタの特徴を分析できる。
→クラスタごとに効果的なクーポンを配るなど、戦略が建てれる。